import os
AddOption("--compiler",
		  dest="compiler",
		  action="store",
		  choices=["clang++", "g++"],
		  default="clang++",
		  help="compiler to use")


simulator_env = Environment(
	CXX = GetOption("compiler"),
	CXXFLAGS = Split(
		"-std=c++11 -Wall -Wextra -pedantic -O2 " +
		"-pipe -pthread -finline-functions -Wreorder"),
	CPPDEFINES = Split(""),
	CPPPATH = Split("../../../"),  # relatie (starts from "build")
	LIBS = Split(""),
	LIBPATH = Split(""),
	LINKFLAGS = Split(""),
	DESTDIR = "../bin"
)

# clang colors
simulator_env['ENV']['TERM'] = os.environ['TERM']
SConscript('SConscript', variant_dir='build', exports=["simulator_env"])
