Import("simulator_env")
target_exe = "bin/simulator"
cxx_units = Glob("*.cxx")
simulator_env.Program(
	target=target_exe,
	source=simulator_env.SharedObject(cxx_units)
)
simulator_env.Install(simulator_env["DESTDIR"], target_exe)
